sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '0.12'
branches:
  only:
    - master
before_install:
  - rm -rf node_modules
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:once
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
